name: Update flake

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/update-flake-lock@v29
        with:
          branch: update_flake_lock_action
          commit-msg: flake update
          pr-title: flake update
